spring:
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    port: 15672
    exchange:
      answering: answering
    routingkey:
      answering: answering
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/mail_sender
    username: aleksey
    password: aleksey
    hikari:
      connection-timeout: 40000
      idle-timeout: 600000
      maxLifetime: 1200000
      auto-commit: true
      minimum-idle: 10
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  level:
    root: info
server:
  port: 8081